title: Leo Young
description: Keep It Simple, Stupid.
leo:
    blog: /blog/
    github: "https://github.com/leoyoung07"
github:
    repository_name: "leoyoung07.github.io"
    repository_url: "https://github.com/leoyoung07/leoyoung07.github.io"
    owner_name: "leoyoung07"
    owner_url: "https://github.com/leoyoung07"
theme: 
